import Header from '@/components/global/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen  flex flex-col items-center">
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
